version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bd_products
      MYSQL_USER: maxivaz
      MYSQL_PASSWORD: Tiburcio123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: maximogarmasar/api-product:latest
    container_name: api-product
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: bd_products
      DB_USER: maxivaz
      DB_PASS: Tiburcio123
      PORT: 3000

volumes:
  db_data: