services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bd_products
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: maximogarmasar/api-product:latest
    container_name: api-product
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db          # El hostname del contenedor MySQL
      DB_PORT: 3306        # Puerto MySQL interno en Docker (3306)
      DB_NAME: bd_products # Nombre de la base de datos
      DB_USER: root     # Usuario MySQL
      DB_PASS: pass # Contraseña del usuario
      PORT: 3000           # Puerto en el que corre la API

volumes:
  db_data:
